/* ═══════════════════════════════════════════════════════════════
   Markdown for agents (owner: GEO). 04-geo §4.4.
   `curl -H "Accept: text/markdown" https://<domain>/precios/` returns the page's
   <path>index.md mirror (generated by build/lib/machine.mjs from the same content
   as the HTML) with Content-Type text/markdown, Vary: Accept, X-Robots-Tag: noindex
   and a Link rel=canonical to the HTML URL.
   Routing is declared here (config below) and NOT in netlify.toml:
     - path "/*" minus static files (assets, models, .md/.txt/.xml/.json…),
     - header matching: only requests whose Accept contains text/markdown invoke it,
       so normal browser traffic never does (no cost, no latency).
   The function repeats every guard (method, Accept q-values, file paths) so it stays
   correct even where header matching is not applied. It never throws: on any problem
   it returns nothing and Netlify serves the normal static response.
   ═══════════════════════════════════════════════════════════════ */

/** q-value of a media type in an Accept header (0 when absent). */
function qOf(accept, type) {
  let best = 0;
  for (const part of accept.split(',')) {
    const [mt, ...params] = part.trim().split(';').map((s) => s.trim());
    if (mt.toLowerCase() !== type) continue;
    const q = params.find((p) => /^q=/i.test(p));
    best = Math.max(best, q ? parseFloat(q.slice(2)) || 0 : 1);
  }
  return best;
}

export default async (request) => {
  try {
    if (request.method !== 'GET' && request.method !== 'HEAD') return;
    const url = new URL(request.url);
    const accept = request.headers.get('accept') || '';
    const md = qOf(accept, 'text/markdown');
    if (md === 0 || md < qOf(accept, 'text/html')) return; // browsers and HTML-first clients: untouched
    const last = url.pathname.split('/').pop();
    if (last && last.includes('.')) return; // files keep their own type
    const dir = url.pathname.endsWith('/') ? url.pathname : `${url.pathname}/`;
    const res = await fetch(new URL(`${dir}index.md`, url.origin), { headers: { accept: 'text/markdown' } });
    if (!res.ok) return; // no mirror (utility pages, 404): normal response
    const body = await res.text();
    return new Response(request.method === 'HEAD' ? null : body, {
      status: 200,
      headers: {
        'content-type': 'text/markdown; charset=utf-8',
        vary: 'Accept',
        'x-robots-tag': 'noindex',
        'x-markdown-tokens': String(Math.ceil(body.length / 4)),
        link: `<${url.origin}${dir}>; rel="canonical"`,
        'cache-control': 'public, max-age=0, must-revalidate',
      },
    });
  } catch {
    return; // never break the page: fall through to the static response
  }
};

export const config = {
  path: '/*',
  excludedPath: ['/assets/*', '/lib/*', '/models/*', '/.netlify/*', '/*.md', '/*.txt', '/*.xml', '/*.json', '/*.webmanifest', '/*.ico', '/*.png', '/*.svg'],
  header: { accept: 'text/markdown' }, // regex on the Accept header: invoked only when Markdown is requested
  method: ['GET', 'HEAD'],
};
